# Generated by Django 5.2.14 on 2026-06-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlinkMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(db_index=True, verbose_name='체크 타임스탬프')),
                ('time_unit', models.CharField(default='1s', max_length=5)),
                ('total_collected_count', models.BigIntegerField(verbose_name='총 소비 데이터 개수')),
                ('total_error_count', models.IntegerField(verbose_name='에러 수')),
                ('error_rate_percentage', models.FloatField(verbose_name='에러율 퍼센티지')),
                ('average_latency_ms', models.FloatField(verbose_name='평균 처리 지연 시간')),
                ('max_latency_ms', models.FloatField(verbose_name='최대 처리 지연 시간')),
                ('unique_market_count', models.IntegerField(verbose_name='활성 마켓 수')),
                ('total_trade_volume_krw', models.FloatField(verbose_name='초당 총 거래 대금')),
            ],
            options={
                'db_table': 'flink_realtime_metric',
                'ordering': ['-checked_at'],
            },
        ),
    ]
