# Generated by Django 5.2.14 on 2026-06-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flink_metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlinkMarketMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(db_index=True, verbose_name='체크 타임스탬프')),
                ('market', models.CharField(db_index=True, max_length=20, verbose_name='마켓 코드')),
                ('time_unit', models.CharField(default='1s', max_length=5)),
                ('collected_count', models.BigIntegerField(verbose_name='마켓별 소비 데이터 개수')),
                ('error_count', models.IntegerField(verbose_name='마켓별 에러 수')),
                ('error_rate_percentage', models.FloatField(verbose_name='마켓별 에러율 퍼센티지')),
                ('average_latency_ms', models.FloatField(verbose_name='평균 처리 지연 시간')),
                ('max_latency_ms', models.FloatField(verbose_name='최대 처리 지연 시간')),
                ('trade_volume_krw', models.FloatField(verbose_name='초당 거래 대금')),
            ],
            options={
                'db_table': 'flink_market_metric',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['market', '-checked_at'], name='flink_marke_market_cd8321_idx')],
            },
        ),
    ]
