# Generated by Django 5.2.14 on 2026-05-20 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0006_alter_tickerdate_delisting_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='윈도우 시작가')),
                ('end_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='윈도우 끝가')),
                ('change_rate', models.FloatField(verbose_name='변동률')),
                ('status', models.CharField(max_length=15, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_code', models.ForeignKey(db_column='market_code', on_delete=django.db.models.deletion.CASCADE, to='market_data.market')),
            ],
            options={
                'verbose_name': '급락 로그',
                'verbose_name_plural': '급락 로그 목록',
                'db_table': 'drop_logs',
            },
        ),
    ]
