# Generated by Django 5.2.14 on 2026-05-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('detected_change', models.DecimalField(decimal_places=6, max_digits=10)),
                ('alert_type', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('market_code', models.ForeignKey(db_column='market_code', on_delete=django.db.models.deletion.CASCADE, to='market_data.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'alert_log',
            },
        ),
    ]
