# Generated by Django 5.2.14 on 2026-05-18 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('korean_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
                ('warning', models.BooleanField(default=False, null=True)),
                ('price_fluc', models.BooleanField(default=False, null=True)),
                ('vol_soar', models.BooleanField(default=False, null=True)),
                ('dep_amt_soar', models.BooleanField(default=False, null=True)),
                ('global_diff', models.BooleanField(default=False, null=True)),
                ('small_acc_conc', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='TickerDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(default='ticker', max_length=10)),
                ('op', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='시가(op)')),
                ('hp', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='고가(hp)')),
                ('lp', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='저가(lp)')),
                ('tp', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='현재체결가(tp)')),
                ('pcp', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='전일종가(pcp)')),
                ('c', models.CharField(max_length=4, verbose_name='전일대비상태(c)')),
                ('cp', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='전일대비변동액(cp)')),
                ('scp', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='부호있는변동액(scp)')),
                ('cr', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='전일대비변동률(cr)')),
                ('scr', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='부호있는변동률(scr)')),
                ('ab', models.CharField(max_length=3, verbose_name='매수매도구분(ab)')),
                ('tv', models.DecimalField(decimal_places=8, max_digits=25, verbose_name='최근체결량(tv)')),
                ('atv', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='당일누적체결량(atv)')),
                ('atp', models.DecimalField(decimal_places=4, max_digits=30, verbose_name='당일누적거래대금(atp)')),
                ('tdt', models.CharField(max_length=8, verbose_name='최근체결날짜st(tdt)')),
                ('ttm', models.CharField(max_length=6, verbose_name='최근체결시각st(ttm)')),
                ('ttms', models.BigIntegerField(verbose_name='체결타임스탬프ms(ttms)')),
                ('tms', models.BigIntegerField(db_index=True, verbose_name='타임스탬프ms(tms)')),
                ('h52wp', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='52주최고가(h52wp)')),
                ('h52wdt', models.CharField(max_length=10, verbose_name='52주최고가달성일(h52wdt)')),
                ('l52wp', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='52주최저가(l52wp)')),
                ('l52wdt', models.CharField(max_length=10, verbose_name='52주최저가달성일(l52wdt)')),
                ('ms', models.CharField(max_length=10, verbose_name='마켓상태(ms)')),
                ('its', models.BooleanField(default=False, verbose_name='거래정지여부(its)')),
                ('dd', models.CharField(blank=True, max_length=10, null=True, verbose_name='상장폐지일(dd)')),
                ('mw', models.CharField(max_length=10, verbose_name='유의종목여부(mw)')),
                ('atp24h', models.DecimalField(decimal_places=4, max_digits=30, verbose_name='24시간누적거래대금(atp24h)')),
                ('acv24h', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='24시간누적거래량(atv24h)')),
                ('st', models.CharField(max_length=10, verbose_name='정산상태(st)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_code', models.ForeignKey(db_column='market_code', on_delete=django.db.models.deletion.CASCADE, to='market_data.market')),
            ],
            options={
                'db_table': 'ticker_date',
            },
        ),
    ]
