# Generated by Django 5.2.14 on 2026-05-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('korean_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
                ('warning', models.BooleanField(default=False, null=True)),
                ('price_fluc', models.BooleanField(default=False, null=True)),
                ('vol_soar', models.BooleanField(default=False, null=True)),
                ('dep_amt_soar', models.BooleanField(default=False, null=True)),
                ('global_diff', models.BooleanField(default=False, null=True)),
                ('small_acc_conc', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='TickerDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('change_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('trade_vol', models.DecimalField(decimal_places=8, max_digits=20)),
                ('acc_vol_24h', models.DecimalField(decimal_places=8, max_digits=30)),
                ('acc_amt_24h', models.DecimalField(decimal_places=4, max_digits=30)),
                ('ask_bid', models.CharField(max_length=3)),
                ('trade_ts', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_code', models.ForeignKey(db_column='market_code', on_delete=django.db.models.deletion.CASCADE, to='market_data.market')),
            ],
            options={
                'db_table': 'ticker_date',
            },
        ),
    ]
