# Generated by Django 5.2.14 on 2026-05-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_rename_atp_tickerdate_acc_trade_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerdate',
            name='acc_ask_volume',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=30, verbose_name='누적매도량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickerdate',
            name='acc_bid_volume',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=30, verbose_name='누적매수량'),
            preserve_default=False,
        ),
    ]
