# Generated by Django 5.2.14 on 2026-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_tickerdate_acc_ask_volume_tickerdate_acc_bid_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdate',
            name='change',
            field=models.CharField(max_length=10, verbose_name='전일대비상태(c)'),
        ),
        migrations.AlterField(
            model_name='tickerdate',
            name='market_state',
            field=models.CharField(max_length=20, verbose_name='마켓상태(ms)'),
        ),
        migrations.AlterField(
            model_name='tickerdate',
            name='market_warning',
            field=models.CharField(max_length=20, verbose_name='유의종목여부(mw)'),
        ),
        migrations.AlterField(
            model_name='tickerdate',
            name='stream_type',
            field=models.CharField(max_length=20, verbose_name='정산상태(st)'),
        ),
    ]
