# Generated by Django 5.2.14 on 2026-05-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_alter_tickerdate_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdate',
            name='data_type',
            field=models.CharField(default='ticker', max_length=20),
        ),
    ]
