# Generated by Django 5.2.14 on 2026-05-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_alter_tickerdate_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdate',
            name='delisting_date',
            field=models.JSONField(blank=True, max_length=10, null=True, verbose_name='상장폐지일(dd)'),
        ),
        migrations.AlterField(
            model_name='tickerdate',
            name='market_state',
            field=models.CharField(max_length=40, verbose_name='마켓상태(ms)'),
        ),
    ]
