# Generated by Django 5.2.14 on 2026-05-22 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0006_alter_tickerdate_delisting_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadTickerDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(default='ticker', max_length=20)),
                ('opening_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='시가(op)')),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='고가(hp)')),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='저가(lp)')),
                ('trade_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='현재체결가(tp)')),
                ('prev_closing_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='전일종가(pcp)')),
                ('change', models.CharField(max_length=10, verbose_name='전일대비상태(c)')),
                ('change_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='전일대비변동액(cp)')),
                ('signed_change_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='부호있는변동액(scp)')),
                ('change_rate', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='전일대비변동률(cr)')),
                ('signed_change_rate', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='부호있는변동률(scr)')),
                ('ask_bid', models.CharField(max_length=3, verbose_name='매수매도구분(ab)')),
                ('trade_volume', models.DecimalField(decimal_places=8, max_digits=25, verbose_name='최근체결량(tv)')),
                ('acc_trade_volume', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='당일누적체결량(atv)')),
                ('acc_trade_price', models.DecimalField(decimal_places=4, max_digits=30, verbose_name='당일누적거래대금(atp)')),
                ('acc_ask_volume', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='누적매도량')),
                ('acc_bid_volume', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='누적매수량')),
                ('trade_date', models.CharField(max_length=8, verbose_name='최근체결날짜st(tdt)')),
                ('trade_time', models.CharField(max_length=6, verbose_name='최근체결시각st(ttm)')),
                ('trade_timestamp', models.BigIntegerField(verbose_name='체결타임스탬프ms(ttms)')),
                ('timestamp', models.BigIntegerField(db_index=True, verbose_name='타임스탬프ms(tms)')),
                ('highest_52_week_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='52주최고가(h52wp)')),
                ('highest_52_week_date', models.CharField(max_length=10, verbose_name='52주최고가달성일(h52wdt)')),
                ('lowest_52_week_price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='52주최저가(l52wp)')),
                ('lowest_52_week_date', models.CharField(max_length=10, verbose_name='52주최저가달성일(l52wdt)')),
                ('market_state', models.CharField(max_length=40, verbose_name='마켓상태(ms)')),
                ('is_trading_suspended', models.BooleanField(default=False, verbose_name='거래정지여부(its)')),
                ('delisting_date', models.JSONField(blank=True, max_length=10, null=True, verbose_name='상장폐지일(dd)')),
                ('market_warning', models.CharField(max_length=20, verbose_name='유의종목여부(mw)')),
                ('acc_trade_price_24h', models.DecimalField(decimal_places=4, max_digits=30, verbose_name='24시간누적거래대금(atp24h)')),
                ('acc_trade_volume_24h', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='24시간누적거래량(atv24h)')),
                ('stream_type', models.CharField(max_length=20, verbose_name='정산상태(st)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_log', models.CharField(max_length=255, verbose_name='에러로그')),
                ('market_code', models.ForeignKey(db_column='market_code', on_delete=django.db.models.deletion.CASCADE, to='market_data.market')),
            ],
            options={
                'db_table': 'BadTickerDate',
            },
        ),
    ]
