# Generated by Django 5.2.14 on 2026-05-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0007_badtickerdate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='badtickerdate',
            table='bad_ticker_date',
        ),
    ]
