# Generated by Django 5.2.14 on 2026-06-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0009_remove_badtickerdate_acc_ask_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
